import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

/// Builds a simple one-page A4 data sheet (title + standard + a two-column
/// table of the same label/value rows shown in the Dimensions/Rating/
/// Bolting tabs) and opens the platform share/print sheet for it.
///
/// Kept deliberately simple (one table, no branding assets) so it has no
/// dependency on bundled fonts/images — those would need to be added to
/// pubspec assets and are easy to get wrong without being able to run the
/// app here to check the render.
Future<void> shareDataSheet({
  required String title,
  required String standard,
  required Map<String, String> rows,
}) async {
  final doc = pw.Document();

  doc.addPage(
    pw.Page(
      pageFormat: PdfPageFormat.a4,
      build: (pw.Context context) {
        return pw.Padding(
          padding: const pw.EdgeInsets.all(32),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(title, style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 4),
              pw.Text(standard, style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
              pw.SizedBox(height: 20),
              pw.Table(
                border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.5),
                columnWidths: const {0: pw.FlexColumnWidth(2), 1: pw.FlexColumnWidth(3)},
                children: rows.entries
                    .map(
                      (e) => pw.TableRow(children: [
                        pw.Padding(
                          padding: const pw.EdgeInsets.all(6),
                          child: pw.Text(e.key, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
                        ),
                        pw.Padding(
                          padding: const pw.EdgeInsets.all(6),
                          child: pw.Text(e.value, style: const pw.TextStyle(fontSize: 10)),
                        ),
                      ]),
                    )
                    .toList(),
              ),
              pw.SizedBox(height: 24),
              pw.Text(
                'Generated by Piping Data Pro for quick reference. Verify against the '
                'governing code edition and project specification before use in real '
                'engineering work.',
                style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
              ),
            ],
          ),
        );
      },
    ),
  );

  final bytes = await doc.save();
  final safeName = title.replaceAll(RegExp(r'[^A-Za-z0-9]+'), '_');
  await Printing.sharePdf(bytes: bytes, filename: '$safeName.pdf');
}
